name: Development Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Restore dependencies
      run: cd CICDPractice/ && dotnet restore
      
    - name: Build
      run: cd CICDPractice/ && dotnet build --configuration Debug --no-restore /p:DebugType=None
      
    - name: Dotnet publish
      run: cd CICDPractice/ && dotnet publish --self-contained false /p:DebugType=None
      
    - name: Upload Build Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Publish
        path: /home/runner/work/CICDPractice/CICDPractice/CICDPractice/bin/Debug/netcoreapp3.1/publish/
