name: Production Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Restore dependencies
      run: cd CICDPractice/ && dotnet restore
      
    - name: Build
      run: cd CICDPractice/ && dotnet build --configuration Release --no-restore /p:DebugType=None
          
    - name: Dotnet publish
      run: dotnet publish CICDPractice/CICDPractice.csproj -o Publish/CICDPractice/ -r win-x64 --self-contained false /p:DebugType=None
      
    - name: Upload Build Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Publish
        path: Publish/CICDPractice/
    - name : Deploy to Azure App service
      uses: azure/webapps-deploy@v2
      with:
        app-name: CICDPracticeApp
        publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
        package: Publish/CICDPractice/
